### ISSUE TITLE
FEATURE: route for unready a player

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#137]
This should be something similar to the `/game/action/ready/{game_id}`.

Route: `/game/action/unready/{game_id}`
Parameter: `user: Player`
Behavior: unready player and save game
return on success: `{'status': f'{user.username} is unready'}`

Error handling:

- catch wrong game id
- catch player not joined
- catch player not ready

**Comment by abant07** [comment]
Hi @Segelzwerg 

For this issue, I am a little confused about what I would need to do. Would I need to create a separate function that makes a player unready? And in doing so, I have to make sure my code can catch the wrong game id, catch when a player not joined, and catch when a player not ready?

Thanks

**Comment by Segelzwerg** [comment]
> Hi @Segelzwerg
> 
> For this issue, I am a little confused about what I would need to do. Would I need to create a separate function that makes a player unready? 
Yes, that needs to be a new route and a new therefore a new function.

And in doing so, I have to make sure my code can catch the wrong game id, catch when a player not joined, and catch when a player not ready?

Yes, you need also to write tests, that test this behavior. There are plenty of tests in the repo already, where you can have a look at how this works.

**Comment by abant07** [comment]
@Segelzwerg 

I would like to be assigned to this issue. I will let you know if I have any further questions.

Thank you

**Comment by abant07** [comment]
Do I need to write a method for each error (not joined, wrong id, and not ready) or can I use methods from others that have been documented in the tests folder. For example, could I user the GameNotFoundError class for checking the wrong game id?

**Comment by Segelzwerg** [comment]
> Do I need to write a method for each error (not joined, wrong id, and not ready) or can I use methods from others that have been documented in the tests folder. For example, could I user the GameNotFoundError class for checking the wrong game id?

If there is already a custom error class in the repo, you not can use but you should do so, if there isn't an error matching your case, then you need to create a new one.

**Comment by abant07** [comment]
How do I make a pull request to this issue, because when I try to make a pull request, it is making all the changes to the previous issue I did for logging?

Thanks
