### ISSUE TITLE
DOC: game parameter missing

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#190]
https://github.com/Whist-Team/Whist-Server/blob/65163fde9da02ea51b17f4521829715edc08a87d/whist/server/api/game/create.py#L14-L28

**Comment by Segelzwerg** [comment]
@abant07 there is a hidden parameter inside request that can configure some game settings, but it hasn't been documented yet.

```python
    game_parameter = _set_game_parameter(request, user, pwd_service)
    game = game_service.create_with_pwd(**game_parameter)
    game_id = game_service.add(game)
    return {'game_id': game_id}




def _set_game_parameter(request, user, pwd_service: PasswordService):
    pwd_hash = _get_password(pwd_service, request)
    game_name = _get_game_name(request)
    game_parameter = dict(game_name=game_name,
                          hashed_password=pwd_hash,
                          creator=user)
    min_player = _get_amount_player(request, 'min_player')
    if min_player is not None:
        game_parameter.update({'min_player': min_player})
    max_player = _get_amount_player(request, 'max_player')
    if max_player is not None:
        game_parameter.update({'max_player': max_player})
    return game_parameter
```
    
For the moment it is `min_player` and `max_player`

**Comment by abant07** [comment]
@Segelzwerg 

How would you suggest I document the hidden parameter. Do I need to print it or log it? Also how would I be able to know from the code what this hidden parameter is and what it does?

Thanks

**Comment by Segelzwerg** [comment]
> @Segelzwerg
> 
> How would you suggest I document the hidden parameter? 

You can do this in the docstring documentation of the request parameter

> Do I need to print it or log it? Also how would I be able to know from the code what this hidden parameter is and what it does?
> 
all the information are in my previous comment

**Comment by abant07** [comment]
Hi @Segelzwerg 

So, for this issue, would just need to document the request parameters which are max_player and min_player in a docstring in game.py?

Also, could I be assigned this issue?

Thanks

**Comment by Segelzwerg** [comment]
> So, for this issue, would I just need to document the request parameters, which are max_player and min_player, in a docstring in game.py?
> 

Yes, like it has been done with `game_name`.
