### ISSUE TITLE
DUPLICATE: base player test case

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#225]
https://github.com/Whist-Team/Whist-Server/blob/c3961060ce11674c51997da3e987c633c2ff0bc0/tests/whist/server/services/base_player_test_case.py#L8 is a duplicate of https://github.com/Whist-Team/Whist-Server/blob/c3961060ce11674c51997da3e987c633c2ff0bc0/tests/whist/server/base_player_test_case.py#L8

The first class shall be removed and usages must be replaced with the second.

**Comment by JefvdA** [comment]
Hey, I'm looking to contribute to a open-source project. Is it ok if I handle this issue? If so, could you assing me?

**Comment by Segelzwerg** [comment]
@JefvdA welcome and thank you for taking an interest in our project. I've assigned it to you. Feel free to go ahead. Also if you have any question, please let me know.

**Comment by JefvdA** [comment]
@Segelzwerg no worries, I'll update the PR, and remove correct duplicate this time.
