### ISSUE TITLE
BUG: linting shouldn't fail fast

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#228]
https://github.com/Whist-Team/Whist-Server/blob/bd38dba64b0fcd25856415f6fd3655f145a02bb2/.github/workflows/pylint.yml#L11-L16

**Comment by abant07** [comment]
Hi @Segelzwerg 

I was wondering if I could get a brief description for this issue, because I'm not sure what I would need to do here.

Thanks

**Comment by Segelzwerg** [comment]
> Hi @Segelzwerg 
> 
> I was wondering if I could get a deeper description for this issue, because I'm not sure what I would need to do here.
> 
> Thanks

@abant07 you could have a look at the Whist Core Repo in which it is set not fail fast. It is the same file there. Or you have look at the GitHub documentation fail fast job.

**Comment by abant07** [comment]
So is the objective of this issue to make pylint not fail fast for every issue. If so, where can I find the Whist Core Repo because I don't see it in the "code" tab. Also, does the Whist Core Repo give a hint to why pylint fails fast or is it just code I have to decipher?

Thanks

**Comment by abant07** [comment]
Also, could I be assigned this issue?

Thanks

**Comment by Segelzwerg** [comment]
@abant07 it is almost like this. Pylint shall not fail because one job of the matrix fails, but complete all of them. This way we can identify if a problem is occurring only in a specific python version.

[Whist Core](https://github.com/Whist-Team/Whist-Core) is another repository within the Whist Team organization. BTW. the GitHub actions file structure is the same for all repositories.

**Comment by Segelzwerg** [comment]
@abant07 are you still interested in the issue?

**Comment by abant07** [comment]
Hi @Segelzwerg 

I am not interested anymore in this issue. Thanks for asking
