### ISSUE TITLE
Rename `UserInDb.to_user()` to `UserInDb.to_player()`

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#374]

**Comment by JellyBoonz** [comment]
in which files does the renaming need to occur?

**Comment by Segelzwerg** [comment]
> in which files does the renaming need to occur?

Hi @JellyBoonz the path is whist_server/database/user.py

https://github.com/Whist-Team/Whist-Server/blob/73038f864ce1ccc30829d731cdd9b71b63759091/whist_server/database/user.py#L47

**Comment by JellyBoonz** [comment]
Wanna assign it to me?
