### ISSUE TITLE
Test for HTTP/400

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#75]
https://github.com/Whist-Team/Whist-Server/blob/297a7c72c6509ad7184570c39c95c98b54f7c134/tests/whist/server/api/user/test_create.py#L26-L33

This should test for HTTP 400 for missing arguments and an appropriate message.

**Comment by iTitus** [comment]
Sounds good

**Comment by Segelzwerg** [comment]
Accidental duplication of #74

**Comment by iTitus** [comment]
:(
