### ISSUE TITLE
Use HTTP 201 for creation

### ISSUE THREAD

**Issue by Segelzwerg** [Whist-Team/Whist-Server#76]
https://github.com/Whist-Team/Whist-Server/blob/297a7c72c6509ad7184570c39c95c98b54f7c134/tests/whist/server/api/user/test_create.py#L26-L33

This should return HTTP 201: creation.

From [Wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_success)

> 201 Created
The request has been fulfilled, resulting in the creation of a new resource.

**Comment by iTitus** [comment]
I don't think that this is applicable to our API.
I would advocate to just return `200 OK`

**Comment by Segelzwerg** [comment]
Yeah after reading 200 properly I agree.
